"""Single Source of Truth for Wallpaper Categories, Metadata, Heuristics & Prompts.

Adding a new category is as simple as adding ONE entry to CATEGORY_REGISTRY.
All downstream systems (UI sidebar, command bar, classification heuristics,
vision prompts, DB stats, README generator) dynamically derive from this registry.
"""

import re
from typing import Any, Dict, List, Optional, Tuple

CATEGORY_REGISTRY: Dict[str, Dict[str, Any]] = {
    "Abstract": {
        "description": "Gradients, geometric shapes, 3D renders, fluid art",
        "priority": 70,
        "patterns": [
            (r"\babstract\b", 4),
            (r"\bgradient\b", 3),
            (r"\bgeometric\b", 3),
            (r"\btexture\b", 2),
            (r"\bpattern\b", 2),
            (r"\bpoly\b", 2),
            (r"\bfluid\b", 3),
            (r"\bfractal\b", 3),
            (r"\b3d\s*render\b", 3),
            (r"\brender\b", 2),
            (r"\bshape\b", 2),
            (r"\blow\s*poly\b", 3),
            (r"\bmandala\b", 3),
            (r"\bswirl\b", 2),
            (r"\bmarble\b", 2),
            (r"\bink\b", 1),
            (r"\bsplash\b", 2),
            (r"\bwave\b", 1),
            (r"\bvector\b", 2),
            (r"\bsymmetric\b", 2),
            (r"\bkaleidoscope\b", 3),
        ],
        "prompt": "an abstract colorful gradient, 3d render, or geometric pattern",
        "synonyms": ["abstract", "gradient", "geometry", "fractal", "render", "fluid", "mandala"],
    },
    "Animals": {
        "description": "Wildlife, cats, dogs, wolves, birds, marine life",
        "priority": 85,
        "patterns": [
            (r"\banimals?\b", 4),
            (r"\bwildlife\b", 4),
            (r"\bcat\b", 3),
            (r"\bcats\b", 3),
            (r"\bdog\b", 3),
            (r"\bdogs\b", 3),
            (r"\blion\b", 3),
            (r"\btiger\b", 3),
            (r"\bwolf\b", 3),
            (r"\bwolves\b", 3),
            (r"\bbird\b", 3),
            (r"\bbirds\b", 3),
            (r"\beagle\b", 3),
            (r"\bfox\b", 3),
            (r"\bbear\b", 3),
            (r"\bdeer\b", 3),
            (r"\bhorse\b", 3),
            (r"\bhorses\b", 3),
            (r"\belephant\b", 3),
            (r"\bshark\b", 3),
            (r"\bwhale\b", 3),
            (r"\bdolphin\b", 3),
            (r"\bturtle\b", 3),
            (r"\bpanda\b", 3),
            (r"\bred\s*panda\b", 4),
            (r"\boctopus\b", 3),
            (r"\bjellyfish\b", 3),
            (r"\bzebra\b", 3),
            (r"\bgiraffe\b", 3),
            (r"\bpeacock\b", 3),
            (r"\bowl\b", 3),
            (r"\bfalcon\b", 3),
            (r"\bhawk\b", 3),
            (r"\bparrot\b", 3),
            (r"\bhedgehog\b", 3),
            (r"\brabbit\b", 3),
            (r"\bsnake\b", 3),
            (r"\bfrog\b", 3),
            (r"\bfish\b", 2),
            (r"\bfishes\b", 2),
            (r"\bmarine\b", 2),
            (r"\bunderwater\b", 2),
            (r"\bfur\b", 1),
            (r"\bfeather\b", 1),
        ],
        "prompt": "a wild animal, pet cat, dog, wolf, bird, or wildlife photography",
        "synonyms": ["animal", "animals", "wildlife", "pets", "fauna", "nature"],
    },
    "Anime": {
        "description": "Anime, manga, waifu, chibi, Ghibli, vtubers, gacha games",
        "priority": 120,
        "patterns": [
            (r"\banime\b", 5),
            (r"\bmanga\b", 5),
            (r"\bwaifu\b", 5),
            (r"\bchibi\b", 4),
            (r"\bghibli\b", 5),
            (r"\bpikachu\b", 4),
            (r"\bpokemon\b", 4),
            (r"\bcharizard\b", 4),
            (r"\bbulbasaur\b", 4),
            (r"\bcharmander\b", 4),
            (r"\beevee\b", 4),
            (r"\bgengar\b", 4),
            (r"\bgenshin\b", 5),
            (r"\bhonkai\b", 5),
            (r"\bstar\s*rail\b", 5),
            (r"\bzenless\b", 5),
            (r"\bnaruto\b", 5),
            (r"\bdragon\s*ball\b", 5),
            (r"\bone\s*piece\b", 5),
            (r"\battack\s*on\s*titan\b", 5),
            (r"\bmy\s*hero\b", 5),
            (r"\bdemon\s*slayer\b", 5),
            (r"\bjujutsu\s*kaisen\b", 5),
            (r"\bspy\s*x\s*family\b", 5),
            (r"\bchainsaw\s*man\b", 5),
            (r"\bdeath\s*note\b", 5),
            (r"\bfullmetal\b", 5),
            (r"\bcowboy\s*bebop\b", 5),
            (r"\bevangelion\b", 5),
            (r"\bsailor\s*moon\b", 5),
            (r"\bstudio\s*ghibli\b", 5),
            (r"\bmakoto\s*shinkai\b", 5),
            (r"\byour\s*name\b", 5),
            (r"\bhayao\s*miyazaki\b", 5),
            (r"\bvtuber\b", 4),
            (r"\bhololive\b", 5),
            (r"\bnijisanji\b", 5),
            (r"\bvocaloid\b", 5),
            (r"\bhatsune\s*miku\b", 5),
            (r"\bkagamine\b", 5),
            (r"\b初音\b", 5),
            (r"\b Anime \b", 5),
            (r"\bcartoon\b", 2),
            (r"\bjapan\b", 1),
            (r"\bjapanese\b", 1),
        ],
        "prompt": "an anime character or japanese manga animation artwork",
        "synonyms": ["anime", "manga", "waifu", "chibi", "japanese", "otaku"],
    },
    "Architecture": {
        "description": "Buildings, interiors, cityscapes, urban design",
        "priority": 80,
        "patterns": [
            (r"\barchitecture\b", 5),
            (r"\bbuilding\b", 3),
            (r"\bbuildings\b", 3),
            (r"\bskyscraper\b", 3),
            (r"\bskyscrapers\b", 3),
            (r"\bcityscape\b", 3),
            (r"\burban\b", 2),
            (r"\binterior\b", 3),
            (r"\broom\b", 2),
            (r"\bhouse\b", 2),
            (r"\bapartment\b", 2),
            (r"\bbridge\b", 3),
            (r"\btunnel\b", 3),
            (r"\bstair\b", 2),
            (r"\bcorridor\b", 2),
            (r"\bfacade\b", 3),
            (r"\bmodern\s*architecture\b", 4),
            (r"\bclassical\s*architecture\b", 4),
            (r"\bgothic\s*architecture\b", 4),
            (r"\btokyo\s*tower\b", 4),
            (r"\beiffel\s*tower\b", 4),
            (r"\bempire\s*state\b", 4),
            (r"\bburj\s*khalifa\b", 4),
            (r"\bsagrada\s*familia\b", 4),
            (r"\blouvre\b", 3),
            (r"\bcolosseum\b", 3),
            (r"\bcastle\b", 2),
            (r"\bpalace\b", 2),
            (r"\bmuseum\b", 2),
            (r"\bchurch\b", 2),
            (r"\bcathedral\b", 2),
            (r"\btemple\b", 2),
            (r"\bmosque\b", 2),
            (r"\bpagoda\b", 2),
            (r"\bconcrete\b", 1),
            (r"\bglass\b", 1),
        ],
        "prompt": "an architectural photograph of buildings, skyscrapers, or interiors",
        "synonyms": ["architecture", "building", "cityscape", "interior", "urban"],
    },
    "Art": {
        "description": "Traditional paintings, illustration, concept art, digital painting",
        "priority": 75,
        "patterns": [
            (r"\bart\b", 3),
            (r"\bartwork\b", 4),
            (r"\bpainting\b", 4),
            (r"\billustration\b", 4),
            (r"\bdigital\s*art\b", 4),
            (r"\bconcept\s*art\b", 4),
            (r"\bfan\s*art\b", 4),
            (r"\bmatte\s*painting\b", 4),
            (r"\boil\s*painting\b", 4),
            (r"\bwatercolor\b", 4),
            (r"\bacrylic\b", 3),
            (r"\bpastel\b", 3),
            (r"\bcharcoal\b", 3),
            (r"\bsketch\b", 3),
            (r"\bdrawing\b", 3),
            (r"\bdoodle\b", 2),
            (r"\bportrait\s*art\b", 4),
            (r"\bfine\s*art\b", 4),
            (r"\bmural\b", 3),
            (r"\bgraffiti\b", 3),
            (r"\bstreet\s*art\b", 3),
            (r"\bsurreal\s*art\b", 4),
            (r"\bpop\s*art\b", 4),
            (r"\bimpressionism\b", 4),
            (r"\brenaissance\b", 4),
            (r"\bbaroque\b", 3),
            (r"\bromanticism\b", 3),
        ],
        "prompt": "a traditional or digital painting, illustration, or concept art",
        "synonyms": ["art", "artwork", "painting", "illustration", "concept"],
    },
    "Cars": {
        "description": "Sports cars, supercars, classic cars, motorcycles, racing",
        "priority": 90,
        "patterns": [
            (r"\bcar\b", 3),
            (r"\bcars\b", 3),
            (r"\bauto\b", 2),
            (r"\bautomotive\b", 4),
            (r"\bsupercar\b", 4),
            (r"\bsupercars\b", 4),
            (r"\bsportscar\b", 4),
            (r"\bmuscle\s*car\b", 4),
            (r"\bclassic\s*car\b", 4),
            (r"\bvintage\s*car\b", 4),
            (r"\brace\s*car\b", 4),
            (r"\bracing\b", 2),
            (r"\bmotorsport\b", 4),
            (r"\bnascar\b", 4),
            (r"\bformula\s*1\b", 5),
            (r"\bf1\b", 4),
            (r"\bdrift\b", 3),
            (r"\btuning\b", 3),
            (r"\bmotorcycle\b", 3),
            (r"\bmotorcycles\b", 3),
            (r"\bbike\b", 2),
            (r"\blamborghini\b", 4),
            (r"\bferrari\b", 4),
            (r"\bporsche\b", 4),
            (r"\bmclaren\b", 4),
            (r"\bbugatti\b", 4),
            (r"\bkoenigsegg\b", 4),
            (r"\bpagani\b", 4),
            (r"\brolls\s*royce\b", 4),
            (r"\bbentley\b", 4),
            (r"\bmercedes\b", 3),
            (r"\bbmw\b", 3),
            (r"\baudi\b", 3),
            (r"\btoyota\b", 3),
            (r"\bhonda\b", 3),
            (r"\bnissan\b", 3),
            (r"\bmazda\b", 3),
            (r"\bsubaru\b", 3),
            (r"\bmitsubishi\b", 3),
            (r"\bchevrolet\b", 3),
            (r"\bford\b", 3),
            (r"\bdodge\b", 3),
            (r"\bmustang\b", 3),
            (r"\bcorvette\b", 3),
            (r"\bcamaro\b", 3),
            (r"\bcharger\b", 3),
            (r"\bhellcat\b", 3),
            (r"\br34\b", 3),
            (r"\br35\b", 3),
            (r"\bsupra\b", 3),
            (r"\brx7\b", 3),
            (r"\bnsx\b", 3),
            (r"\bgt3\b", 3),
            (r"\bgt3rs\b", 4),
            (r"\b918\b", 3),
            (r"\bvehicle\b", 2),
            (r"\bvehicles\b", 2),
        ],
        "prompt": "a sports car, supercar, classic car, or racing vehicle",
        "synonyms": ["car", "cars", "supercar", "automotive", "vehicle"],
    },
    "Cyberpunk": {
        "description": "Neon dystopia, high-tech low-life, futuristic cityscapes",
        "priority": 95,
        "patterns": [
            (r"\bcyberpunk\b", 5),
            (r"\bsci\s*fi\b", 3),
            (r"\bscience\s*fiction\b", 3),
            (r"\bdystopia\b", 3),
            (r"\bdystopian\b", 3),
            (r"\bneon\s*city\b", 4),
            (r"\bfuturistic\s*city\b", 4),
            (r"\bfuturistic\b", 2),
            (r"\bhologram\b", 3),
            (r"\bholographic\b", 3),
            (r"\bcyber\b", 3),
            (r"\bnetrunner\b", 4),
            (r"\bsamurai\b", 2),
            (r"\bedgerunners\b", 5),
            (r"\b2077\b", 4),
            (r"\bblade\s*runner\b", 5),
            (r"\bghost\s*in\s*the\s*shell\b", 5),
            (r"\bakira\b", 4),
            (r"\btron\b", 4),
            (r"\bmetropolis\b", 3),
            (r"\bretro\s*futurism\b", 4),
            (r"\bretrowave\b", 3),
            (r"\bsynthwave\b", 3),
            (r"\brain\b", 2),
            (r"\bchrome\b", 2),
            (r"\bneon\s*lights\b", 3),
            (r"\bnight\s*city\b", 3),
            (r"\btokyo\s*night\b", 3),
            (r"\bhong\s*kong\b", 2),
            (r"\bshibuya\b", 2),
        ],
        "prompt": "a cyberpunk neon cityscape with rain, holograms, and futuristic technology",
        "synonyms": ["cyberpunk", "scifi", "dystopia", "neon", "future"],
    },
    "Fantasy": {
        "description": "Dragons, magic, medieval, mythical creatures, epic landscapes",
        "priority": 95,
        "patterns": [
            (r"\bfantasy\b", 5),
            (r"\bmagic\b", 3),
            (r"\bmagical\b", 3),
            (r"\bdragon\b", 4),
            (r"\bdragons\b", 4),
            (r"\belf\b", 3),
            (r"\belves\b", 3),
            (r"\borc\b", 3),
            (r"\bunicorn\b", 4),
            (r"\bphoenix\b", 4),
            (r"\bgriffin\b", 4),
            (r"\bgriffon\b", 4),
            (r"\bmedieval\b", 3),
            (r"\bknight\b", 3),
            (r"\bcastle\b", 3),
            (r"\bfairy\b", 3),
            (r"\bfae\b", 3),
            (r"\bwizard\b", 3),
            (r"\bsorcerer\b", 3),
            (r"\bwitch\b", 3),
            (r"\bwarlock\b", 3),
            (r"\bmage\b", 3),
            (r"\bspell\b", 2),
            (r"\bwarcraft\b", 5),
            (r"\bworld\s*of\s*warcraft\b", 5),
            (r"\bskyrim\b", 5),
            (r"\belders\s*scrolls\b", 5),
            (r"\bdark\s*souls\b", 5),
            (r"\belden\s*ring\b", 5),
            (r"\bbloodborne\b", 5),
            (r"\bdiablo\b", 5),
            (r"\bwitcher\b", 5),
            (r"\bgollum\b", 4),
            (r"\bmiddle\s*earth\b", 5),
            (r"\blord\s*of\s*the\s*rings\b", 5),
            (r"\blotr\b", 5),
            (r"\bhobbit\b", 4),
            (r"\bharry\s*potter\b", 5),
            (r"\bgame\s*of\s*thrones\b", 5),
            (r"\bmythical\b", 3),
            (r"\bmythology\b", 3),
            (r"\bepic\b", 1),
        ],
        "prompt": "a fantasy landscape with dragons, magic, castles, or mythical creatures",
        "synonyms": ["fantasy", "magic", "dragon", "medieval", "mythical"],
    },
    "Food": {
        "description": "Cuisine, drinks, desserts, food photography",
        "priority": 85,
        "patterns": [
            (r"\bfood\b", 4),
            (r"\bcuisine\b", 4),
            (r"\bdessert\b", 4),
            (r"\bdesserts\b", 4),
            (r"\bcake\b", 3),
            (r"\bcoffee\b", 3),
            (r"\btea\b", 2),
            (r"\bwine\b", 3),
            (r"\bbeer\b", 3),
            (r"\bcocktail\b", 3),
            (r"\bpizza\b", 3),
            (r"\bsushi\b", 3),
            (r"\bburger\b", 3),
            (r"\bsteak\b", 3),
            (r"\bfruit\b", 2),
            (r"\bfruits\b", 2),
            (r"\bvegetable\b", 2),
            (r"\bvegetables\b", 2),
            (r"\bchocolate\b", 3),
            (r"\bice\s*cream\b", 3),
            (r"\bdonut\b", 3),
            (r"\bmacaron\b", 3),
            (r"\bcafe\b", 2),
            (r"\brestaurant\b", 2),
            (r"\bkitchen\b", 2),
            (r"\bbaking\b", 2),
            (r"\bgourmet\b", 2),
            (r"\bculinary\b", 3),
        ],
        "prompt": "delicious food, dessert, drink, or culinary photography",
        "synonyms": ["food", "cuisine", "dessert", "drink", "culinary"],
    },
    "Games": {
        "description": "Video games, game art, screenshots, esports",
        "priority": 110,
        "patterns": [
            (r"\bgame\b", 3),
            (r"\bgames\b", 3),
            (r"\bgaming\b", 4),
            (r"\bgameplay\b", 4),
            (r"\bvideo\s*game\b", 4),
            (r"\bscreenshot\b", 3),
            (r"\besports\b", 4),
            (r"\bleague\s*of\s*legends\b", 5),
            (r"\blol\b", 3),
            (r"\bdota\b", 5),
            (r"\bdota2\b", 5),
            (r"\bvalorant\b", 5),
            (r"\bcs2\b", 5),
            (r"\bcounter\s*strike\b", 5),
            (r"\boverwatch\b", 5),
            (r"\bfortnite\b", 5),
            (r"\bminecraft\b", 5),
            (r"\bterraria\b", 5),
            (r"\broblolox\b", 5),
            (r"\broblox\b", 5),
            (r"\bgta\b", 4),
            (r"\bgrand\s*theft\s*auto\b", 5),
            (r"\bred\s*dead\b", 5),
            (r"\bassassins\s*creed\b", 5),
            (r"\bmetal\s*gear\b", 5),
            (r"\btomb\s*raider\b", 5),
            (r"\buncharted\b", 5),
            (r"\bthe\s*last\s*of\s*us\b", 5),
            (r"\bgod\s*of\s*war\b", 5),
            (r"\bhorizon\s*zero\s*dawn\b", 5),
            (r"\bspider\s*man\b", 4),
            (r"\bspiderman\b", 4),
            (r"\bbatman\b", 4),
            (r"\bark\b", 3),
            (r"\bterraria\b", 4),
            (r"\bzelda\b", 5),
            (r"\bbreath\s*of\s*the\s*wild\b", 5),
            (r"\btears\s*of\s*the\s*kingdom\b", 5),
            (r"\bmario\b", 5),
            (r"\bsuper\s*mario\b", 5),
            (r"\bhalo\b", 5),
            (r"\bdoom\b", 5),
            (r"\bwolfenstein\b", 5),
            (r"\bquake\b", 4),
            (r"\bhalf\s*life\b", 5),
            (r"\bportal\b", 4),
            (r"\bteam\s*fortress\b", 5),
            (r"\bapex\s*legends\b", 5),
            (r"\bpubg\b", 5),
            (r"\bcall\s*of\s*duty\b", 5),
            (r"\bcod\b", 3),
            (r"\bwarzone\b", 4),
            (r"\bblack\s*ops\b", 4),
            (r"\bfinal\s*fantasy\b", 5),
            (r"\bkingdom\s*hearts\b", 5),
            (r"\bpersona\b", 5),
            (r"\bsonic\b", 5),
            (r"\bstreet\s*fighter\b", 5),
            (r"\bmortal\s*kombat\b", 5),
            (r"\bsmash\s*bros\b", 5),
            (r"\bresident\s*evil\b", 5),
            (r"\bsilent\s*hill\b", 5),
            (r"\bmetal\s*gear\b", 5),
            (r"\bsolid\s*snake\b", 4),
            (r"\bgaming\b", 4),
            (r"\bplaystation\b", 3),
            (r"\bxbox\b", 3),
            (r"\bnintendo\b", 3),
            (r"\bsteam\b", 2),
        ],
        "prompt": "a video game character, screenshot, or game art",
        "synonyms": ["game", "games", "gaming", "videogame"],
    },
    "Holidays": {
        "description": "Christmas, Halloween, New Year, celebrations",
        "priority": 90,
        "patterns": [
            (r"\bchristmas\b", 5),
            (r"\bhalloween\b", 5),
            (r"\bnew\s*year\b", 4),
            (r"\bthanksgiving\b", 4),
            (r"\bvalentine\b", 4),
            (r"\beaster\b", 4),
            (r"\bhannukah\b", 4),
            (r"\bhanukkah\b", 4),
            (r"\bdiwali\b", 4),
            (r"\blunar\s*new\s*year\b", 4),
            (r"\bchinese\s*new\s*year\b", 4),
            (r"\bfireworks\b", 3),
            (r"\bpumpkin\b", 3),
            (r"\bsanta\b", 3),
            (r"\bsnowman\b", 3),
            (r"\breindeer\b", 3),
            (r"\bspooky\b", 2),
            (r"\btrick\s*or\s*treat\b", 4),
            (r"\bxmas\b", 4),
            (r"\bnoel\b", 3),
            (r"\bholiday\b", 3),
            (r"\bholidays\b", 3),
            (r"\bcelebration\b", 2),
            (r"\bfestival\b", 2),
            (r"\bparty\b", 1),
        ],
        "prompt": "a festive holiday scene such as Christmas, Halloween, or New Year",
            "synonyms": ["holiday", "christmas", "halloween", "new year"],
    },
    "Landscape": {
        "description": "Natural scenery, mountains, forests, beaches, deserts",
        "priority": 80,
        "patterns": [
            (r"\blandscape\b", 5),
            (r"\bscenery\b", 4),
            (r"\bnature\b", 3),
            (r"\bmountain\b", 3),
            (r"\bmountains\b", 3),
            (r"\bforest\b", 3),
            (r"\bforests\b", 3),
            (r"\bbeach\b", 3),
            (r"\bbeaches\b", 3),
            (r"\bocean\b", 3),
            (r"\bsea\b", 3),
            (r"\bdesert\b", 3),
            (r"\bvalley\b", 3),
            (r"\bfield\b", 3),
            (r"\bmeadow\b", 3),
            (r"\bprairie\b", 3),
            (r"\bplateau\b", 3),
            (r"\bcanyon\b", 3),
            (r"\bcliff\b", 3),
            (r"\bwaterfall\b", 3),
            (r"\blake\b", 3),
            (r"\briver\b", 3),
            (r"\bstream\b", 2),
            (r"\bisland\b", 3),
            (r"\btropical\b", 2),
            (r"\bsavanna\b", 3),
            (r"\btundra\b", 3),
            (r"\bglacier\b", 3),
            (r"\bvolcano\b", 3),
            (r"\bnorthern\s*lights\b", 4),
            (r"\baurora\b", 4),
            (r"\bautumn\b", 2),
            (r"\bwinter\b", 2),
            (r"\bspring\b", 2),
            (r"\bsummer\b", 2),
            (r"\bsunset\b", 2),
            (r"\bsunrise\b", 2),
            (r"\bhorizon\b", 2),
            (r"\bpanorama\b", 2),
            (r"\btree\b", 1),
            (r"\btrees\b", 1),
        ],
        "prompt": "a scenic landscape with mountains, forests, beaches, or deserts",
        "synonyms": ["landscape", "scenery", "nature", "mountain", "forest", "beach"],
    },
    "Macro": {
        "description": "Close-up photography of small subjects",
        "priority": 75,
        "patterns": [
            (r"\bmacro\b", 5),
            (r"\bclose\s*up\b", 4),
            (r"\bcloseup\b", 4),
            (r"\bmicro\b", 3),
            (r"\bdetail\b", 2),
            (r"\bextreme\s*close\s*up\b", 5),
            (r"\bdew\b", 2),
            (r"\bdroplet\b", 3),
            (r"\bwater\s*drop\b", 3),
            (r"\beye\s*close\s*up\b", 4),
            (r"\binsect\s*macro\b", 4),
            (r"\bflower\s*macro\b", 4),
        ],
        "prompt": "a macro close-up photograph of a tiny subject",
        "synonyms": ["macro", "closeup", "close-up", "micro"],
    },
    "Minimalism": {
        "description": "Clean, simple, negative space, flat design, OLED-friendly",
        "priority": 85,
        "patterns": [
            (r"\bminimal\b", 5),
            (r"\bminimalism\b", 5),
            (r"\bminimalist\b", 5),
            (r"\bnegative\s*space\b", 4),
            (r"\bsimple\b", 2),
            (r"\bclean\b", 2),
            (r"\bflat\s*design\b", 3),
            (r"\bmonochrome\b", 2),
            (r"\bblack\s*and\s*white\b", 2),
            (r"\bwhite\s*background\b", 3),
            (r"\bdark\s*background\b", 3),
            (r"\boled\b", 4),
            (r"\bamoled\b", 4),
            (r"\bsolid\s*color\b", 3),
            (r"\bplain\b", 2),
            (r"\bquiet\b", 1),
            (r"\bzen\b", 2),
            (r"\bline\s*art\b", 3),
        ],
        "prompt": "a minimalist wallpaper with clean lines, negative space, or solid colors",
        "synonyms": ["minimal", "minimalism", "clean", "simple", "oled"],
    },
    "Miscellaneous": {
        "description": "Uncategorized or mixed content",
        "priority": 10,
        "patterns": [
            (r"\bmisc\b", 4),
            (r"\bmiscellaneous\b", 4),
            (r"\brandom\b", 2),
            (r"\bmixed\b", 2),
            (r"\bvariety\b", 2),
            (r"\buncategorized\b", 3),
        ],
        "prompt": "a miscellaneous wallpaper",
        "synonyms": ["misc", "miscellaneous", "random", "mixed"],
    },
    "Movies": {
        "description": "Film stills, movie posters, cinematic scenes",
        "priority": 100,
        "patterns": [
            (r"\bmovie\b", 4),
            (r"\bmovies\b", 4),
            (r"\bfilm\b", 3),
            (r"\bcinema\b", 3),
            (r"\bcinematic\b", 3),
            (r"\bposter\b", 3),
            (r"\bscene\b", 2),
            (r"\bmarvel\b", 5),
            (r"\bdc\s*comics\b", 5),
            (r"\bavengers\b", 5),
            (r"\bstar\s*wars\b", 5),
            (r"\bstar\s*trek\b", 5),
            (r"\blord\s*of\s*the\s*rings\b", 5),
            (r"\blotr\b", 5),
            (r"\bmatrix\b", 4),
            (r"\binception\b", 4),
            (r"\binterstellar\b", 4),
            (r"\btenet\b", 4),
            (r"\bdune\b", 5),
            (r"\bjames\s*bond\b", 4),
            (r"\bfast\s*and\s*furious\b", 4),
            (r"\bjurassic\s*park\b", 4),
            (r"\bback\s*to\s*the\s*future\b", 4),
            (r"\bindiana\s*jones\b", 4),
            (r"\bmission\s*impossible\b", 4),
            (r"\bthe\s*godfather\b", 4),
            (r"\bpulp\s*fiction\b", 4),
            (r"\bfight\s*club\b", 4),
            (r"\bforrest\s*gump\b", 4),
            (r"\btitanic\b", 4),
            (r"\bgladiator\b", 4),
            (r"\bbraveheart\b", 4),
            (r"\bdeadpool\b", 4),
            (r"\bwolverine\b", 4),
            (r"\biron\s*man\b", 4),
            (r"\bcaptain\s*america\b", 4),
            (r"\bthor\b", 3),
            (r"\bhulk\b", 3),
            (r"\bspider\s*man\b", 4),
            (r"\bspiderman\b", 4),
            (r"\bbatman\b", 4),
            (r"\bsuperman\b", 4),
            (r"\bwonder\s*woman\b", 4),
            (r"\bjoker\b", 3),
            (r"\bharry\s*potter\b", 5),
            (r"\bhunger\s*games\b", 4),
            (r"\btwilight\b", 3),
            (r"\bdisney\b", 4),
            (r"\bpixar\b", 4),
        ],
        "prompt": "a movie poster, film still, or cinematic scene",
        "synonyms": ["movie", "movies", "film", "cinema", "cinematic"],
    },
    "Music": {
        "description": "Musicians, instruments, concerts, album art",
        "priority": 85,
        "patterns": [
            (r"\bmusic\b", 4),
            (r"\bmusical\b", 3),
            (r"\bmusician\b", 4),
            (r"\bsinger\b", 3),
            (r"\bband\b", 3),
            (r"\bconcert\b", 4),
            (r"\bguitar\b", 3),
            (r"\bpiano\b", 3),
            (r"\bdrums\b", 3),
            (r"\bviolin\b", 3),
            (r"\bsaxophone\b", 3),
            (r"\btrumpet\b", 3),
            (r"\bdj\b", 3),
            (r"\bedm\b", 3),
            (r"\balbum\s*art\b", 4),
            (r"\brecord\b", 2),
            (r"\bvinyl\b", 3),
            (r"\bmicrophone\b", 2),
            (r"\bheadphones\b", 3),
            (r"\bspeaker\b", 2),
            (r"\bfestival\b", 2),
            (r"\bstage\b", 2),
            (r"\brock\b", 2),
            (r"\bmetal\b", 1),
            (r"\bjazz\b", 2),
            (r"\bclassical\s*music\b", 3),
            (r"\borchestra\b", 3),
        ],
        "prompt": "music related wallpaper with instruments, concerts, or album art",
        "synonyms": ["music", "musician", "concert", "instrument", "album"],
    },
    "Nature": {
        "description": "Plants, flowers, wildlife, natural textures",
        "priority": 80,
        "patterns": [
            (r"\bnature\b", 4),
            (r"\bnatural\b", 3),
            (r"\bflower\b", 3),
            (r"\bflowers\b", 3),
            (r"\bplant\b", 3),
            (r"\bplants\b", 3),
            (r"\btree\b", 2),
            (r"\btrees\b", 2),
            (r"\bleaf\b", 2),
            (r"\bleaves\b", 2),
            (r"\bgrass\b", 2),
            (r"\bbloom\b", 2),
            (r"\bblossom\b", 2),
            (r"\bcherry\s*blossom\b", 4),
            (r"\bsakura\b", 4),
            (r"\brose\b", 3),
            (r"\bsunflower\b", 3),
            (r"\bdaisy\b", 3),
            (r"\blavender\b", 3),
            (r"\bfern\b", 3),
            (r"\bmoss\b", 3),
            (r"\bbamboo\b", 3),
            (r"\bcactus\b", 3),
            (r"\bsucculent\b", 3),
            (r"\borchid\b", 3),
            (r"\btulip\b", 3),
            (r"\bwisteria\b", 3),
            (r"\bbutterfly\b", 3),
            (r"\bbees\b", 2),
            (r"\bnatural\s*texture\b", 3),
            (r"\borganic\b", 2),
            (r"\bwilderness\b", 2),
        ],
        "prompt": "a nature wallpaper with flowers, plants, trees, or wildlife",
        "synonyms": ["nature", "flower", "plant", "flora", "natural"],
    },
    "Neon": {
        "description": "Neon lights, signs, glowing urban nightlife",
        "priority": 85,
        "patterns": [
            (r"\bneon\b", 5),
            (r"\bneon\s*sign\b", 4),
            (r"\bneon\s*lights\b", 4),
            (r"\bneon\s*glow\b", 4),
            (r"\bglow\b", 2),
            (r"\bglowing\b", 2),
            (r"\bfluorescent\b", 3),
            (r"\belectric\b", 2),
            (r"\bvivid\b", 1),
            (r"\bnightlife\b", 3),
            (r"\bnights\b", 2),
            (r"\bcity\s*lights\b", 3),
            (r"\btokeyo\s*neon\b", 4),
            (r"\bhong\s*kong\b", 2),
            (r"\bshinjuku\b", 3),
            (r"\bshibuya\b", 3),
            (r"\bseoul\b", 2),
        ],
        "prompt": "a neon-lit urban scene with bright glowing signs",
        "synonyms": ["neon", "glow", "night", "lights", "urban"],
    },
    "Other": {
        "description": "Fallback for content that doesn't match any category",
        "priority": 0,
        "patterns": [],
        "prompt": "a wallpaper",
        "synonyms": ["other", "unknown", "uncategorized"],
    },
    "People": {
        "description": "Portraits, fashion, crowds, human subjects",
        "priority": 85,
        "patterns": [
            (r"\bpeople\b", 4),
            (r"\bperson\b", 3),
            (r"\bportrait\b", 4),
            (r"\bportraits\b", 4),
            (r"\bwoman\b", 3),
            (r"\bwomen\b", 3),
            (r"\bman\b", 3),
            (r"\bmen\b", 3),
            (r"\bgirl\b", 2),
            (r"\bboy\b", 2),
            (r"\bfashion\b", 3),
            (r"\bmodel\b", 2),
            (r"\bmodels\b", 2),
            (r"\bcrowd\b", 3),
            (r"\bstreet\s*photography\b", 4),
            (r"\bselfie\b", 3),
            (r"\bface\b", 2),
            (r"\bsilhouette\b", 2),
            (r"\bhuman\b", 2),
            (r"\bcharacter\b", 1),
            (r"\bactor\b", 2),
            (r"\bactress\b", 2),
            (r"\bcelebrity\b", 2),
        ],
        "prompt": "a portrait or photograph of a person or people",
        "synonyms": ["people", "person", "portrait", "human", "fashion"],
    },
    "Pixel Art": {
        "description": "Pixel art, 8-bit, 16-bit, retro game graphics",
        "priority": 95,
        "patterns": [
            (r"\bpixel\s*art\b", 5),
            (r"\bpixelart\b", 5),
            (r"\bpixelated\b", 4),
            (r"\b8\s*bit\b", 4),
            (r"\b16\s*bit\b", 4),
            (r"\b32\s*bit\b", 4),
            (r"\bretro\s*game\b", 4),
            (r"\bbitmap\b", 2),
            (r"\bsprite\b", 3),
            (r"\bsprites\b", 3),
            (r"\bdot\s*art\b", 3),
            (r"\bpoint\s*and\s*click\b", 3),
            (r"\bindie\s*game\b", 3),
            (r"\bplatformer\b", 3),
            (r"\broguelike\b", 3),
            (r"\broguelite\b", 3),
            (r"\bmetroidvania\b", 3),
        ],
        "prompt": "a pixel art wallpaper with 8-bit or 16-bit retro graphics",
        "synonyms": ["pixel", "pixelart", "8bit", "16bit", "retro"],
    },
    "Space": {
        "description": "Planets, galaxies, nebulae, astronauts, cosmos",
        "priority": 90,
        "patterns": [
            (r"\bspace\b", 4),
            (r"\bspaceship\b", 3),
            (r"\bspacecraft\b", 3),
            (r"\bspaceshuttle\b", 3),
            (r"\bastronaut\b", 4),
            (r"\bastronauts\b", 4),
            (r"\bplanet\b", 3),
            (r"\bplanets\b", 3),
            (r"\bearth\b", 2),
            (r"\bmars\b", 2),
            (r"\bjupiter\b", 2),
            (r"\bsaturn\b", 2),
            (r"\bneptune\b", 2),
            (r"\bvenus\b", 2),
            (r"\bmercury\b", 2),
            (r"\bpluto\b", 2),
            (r"\bgalaxy\b", 4),
            (r"\bgalaxies\b", 4),
            (r"\bnebula\b", 4),
            (r"\bnebulae\b", 4),
            (r"\bstars\b", 2),
            (r"\bstarfield\b", 3),
            (r"\bconstellation\b", 3),
            (r"\bblack\s*hole\b", 4),
            (r"\bsupernova\b", 4),
            (r"\bcomet\b", 3),
            (r"\basteroid\b", 3),
            (r"\bmoon\b", 2),
            (r"\bsun\b", 1),
            (r"\bcosmos\b", 3),
            (r"\buniverse\b", 3),
            (r"\bouter\s*space\b", 4),
            (r"\bdeep\s*space\b", 4),
            (r"\bmilky\s*way\b", 4),
            (r"\bspace\s*station\b", 3),
            (r"\biss\b", 3),
            (r"\bnasa\b", 3),
            (r"\bspacex\b", 3),
        ],
        "prompt": "a space wallpaper with planets, galaxies, nebulae, or astronauts",
        "synonyms": ["space", "galaxy", "nebula", "planet", "cosmos"],
    },
    "Sports": {
        "description": "Athletes, stadiums, action sports, fitness",
        "priority": 85,
        "patterns": [
            (r"\bsports?\b", 4),
            (r"\bathlete\b", 4),
            (r"\bathletes\b", 4),
            (r"\bfootball\b", 3),
            (r"\bsoccer\b", 4),
            (r"\bbasketball\b", 4),
            (r"\bbaseball\b", 4),
            (r"\btennis\b", 4),
            (r"\bgolf\b", 3),
            (r"\bhockey\b", 4),
            (r"\bvolleyball\b", 4),
            (r"\brugby\b", 4),
            (r"\bcricket\b", 4),
            (r"\bboxing\b", 4),
            (r"\bmma\b", 4),
            (r"\bUFC\b", 4),
            (r"\bWWE\b", 4),
            (r"\brunning\b", 3),
            (r"\bswimming\b", 3),
            (r"\bsurfing\b", 4),
            (r"\bskate\b", 3),
            (r"\bskateboard\b", 3),
            (r"\bsnowboard\b", 3),
            (r"\bskiing\b", 3),
            (r"\bclimbing\b", 3),
            (r"\byoga\b", 3),
            (r"\bfitness\b", 3),
            (r"\bgym\b", 3),
            (r"\bworkout\b", 3),
            (r"\bstadium\b", 3),
            (r"\barena\b", 3),
            (r"\bolympics\b", 4),
            (r"\bfifa\b", 3),
            (r"\buefa\b", 3),
            (r"\bnba\b", 4),
            (r"\bnfl\b", 4),
            (r"\bnhl\b", 4),
            (r"\bmlb\b", 4),
        ],
        "prompt": "a sports wallpaper with athletes, stadiums, or action",
        "synonyms": ["sports", "sport", "athlete", "fitness", "stadium"],
    },
    "Technology": {
        "description": "Computers, code, circuits, gadgets, futuristic tech",
        "priority": 85,
        "patterns": [
            (r"\btechnology\b", 4),
            (r"\btech\b", 3),
            (r"\bcomputer\b", 3),
            (r"\bcomputers\b", 3),
            (r"\bpc\b", 2),
            (r"\bgaming\s*pc\b", 3),
            (r"\bsetup\b", 2),
            (r"\bworkstation\b", 3),
            (r"\bcode\b", 3),
            (r"\bcoding\b", 3),
            (r"\bprogramming\b", 3),
            (r"\bdeveloper\b", 2),
            (r"\bcircuit\b", 3),
            (r"\bpcb\b", 3),
            (r"\bmotherboard\b", 3),
            (r"\bchip\b", 3),
            (r"\bcpu\b", 3),
            (r"\bgpu\b", 3),
            (r"\bprocessor\b", 3),
            (r"\btransistor\b", 3),
            (r"\bserver\b", 2),
            (r"\bdatacenter\b", 3),
            (r"\bnetwork\b", 2),
            (r"\binternet\b", 2),
            (r"\bphone\b", 2),
            (r"\bsmartphone\b", 2),
            (r"\biphone\b", 2),
            (r"\bandroid\b", 2),
            (r"\bgadget\b", 2),
            (r"\brobot\b", 3),
            (r"\brobots\b", 3),
            (r"\bandroid\s*robot\b", 3),
            (r"\bcyborg\b", 3),
            (r"\bai\s*art\b", 2),
            (r"\bartificial\s*intelligence\b", 3),
            (r"\bquantum\b", 3),
            (r"\bhologram\b", 2),
            (r"\binterface\b", 2),
            (r"\bui\b", 2),
            (r"\bterminal\b", 3),
            (r"\bhacker\b", 3),
            (r"\blinux\b", 3),
            (r"\bunix\b", 3),
            (r"\bwindows\b", 2),
            (r"\bmac\b", 2),
            (r"\bapple\b", 1),
        ],
        "prompt": "a technology wallpaper with computers, circuits, code, or futuristic tech",
        "synonyms": ["technology", "tech", "computer", "code", "circuit"],
    },
    "Typography": {
        "description": "Text-based art, quotes, calligraphy, logo designs",
        "priority": 80,
        "patterns": [
            (r"\btypography\b", 5),
            (r"\btypographic\b", 5),
            (r"\bquote\b", 3),
            (r"\bquotes\b", 3),
            (r"\bcalligraphy\b", 4),
            (r"\blettering\b", 4),
            (r"\bfont\b", 3),
            (r"\btext\s*art\b", 4),
            (r"\bword\s*art\b", 4),
            (r"\blogo\b", 2),
            (r"\bposter\s*quote\b", 3),
            (r"\bmotivational\b", 2),
            (r"\bgraffiti\s*letter\b", 3),
            (r"\bneon\s*sign\b", 2),
            (r"\bslogan\b", 2),
        ],
        "prompt": "a typography wallpaper with text, quotes, or lettering",
        "synonyms": ["typography", "text", "quote", "calligraphy", "lettering"],
    },
    "Vaporwave": {
        "description": "Vaporwave, retrowave, synthwave, 80s/90s aesthetics",
        "priority": 90,
        "patterns": [
            (r"\bvaporwave\b", 5),
            (r"\bretrowave\b", 5),
            (r"\bsynthwave\b", 5),
            (r"\b80s\b", 3),
            (r"\b90s\b", 3),
            (r"\b1980s\b", 3),
            (r"\b1990s\b", 3),
            (r"\boutrun\b", 4),
            (r"\bpalm\s*tree\b", 2),
            (r"\bstatue\b", 2),
            (r"\bglitch\b", 3),
            (r"\bchrome\b", 2),
            (r"\bgrid\b", 2),
            (r"\bsunset\s*drive\b", 3),
            (r"\baesthetic\b", 2),
            (r"\bseapunk\b", 4),
            (r"\bmallsoft\b", 4),
            (r"\bchillwave\b", 4),
            (r"\bdreamwave\b", 4),
            (r"\blofi\b", 3),
            (r"\bcassette\b", 2),
            (r"\bvhs\b", 3),
        ],
        "prompt": "a vaporwave or retrowave scene with palm trees, sunsets, and 80s neon aesthetics",
        "synonyms": ["vaporwave", "retrowave", "synthwave", "80s", "aesthetic"],
    },
    "Weapons": {
        "description": "Firearms, swords, historical weapons, military gear",
        "priority": 85,
        "patterns": [
            (r"\bweapon\b", 4),
            (r"\bweapons\b", 4),
            (r"\bgun\b", 3),
            (r"\bguns\b", 3),
            (r"\bfirearm\b", 4),
            (r"\brifle\b", 3),
            (r"\bpistol\b", 3),
            (r"\bsniper\b", 3),
            (r"\bshotgun\b", 3),
            (r"\bassault\s*rifle\b", 4),
            (r"\bsword\b", 3),
            (r"\bswords\b", 3),
            (r"\bkatana\b", 4),
            (r"\blongsword\b", 4),
            (r"\bexcalibur\b", 4),
            (r"\bbow\b", 2),
            (r"\bcrossbow\b", 3),
            (r"\bspear\b", 3),
            (r"\baxe\b", 3),
            (r"\bknife\b", 3),
            (r"\bdagger\b", 3),
            (r"\bmilitary\b", 3),
            (r"\barmy\b", 2),
            (r"\bsoldier\b", 3),
            (r"\bwar\b", 2),
            (r"\btank\b", 3),
            (r"\bfighter\s*jet\b", 3),
            (r"\b battleship\b", 3),
            (r"\barmor\b", 2),
            (r"\bshield\b", 2),
            (r"\bmedieval\s*weapon\b", 4),
            (r"\bmodern\s*warfare\b", 4),
            (r"\bcall\s*of\s*duty\b", 3),
        ],
        "prompt": "a wallpaper featuring firearms, swords, or military equipment",
        "synonyms": ["weapon", "weapons", "gun", "sword", "military"],
    },
}

# Legacy flat aliases for downstream imports
CATEGORIES = list(CATEGORY_REGISTRY.keys())
CATEGORY_PATTERNS: Dict[str, List[str]] = {
    cat: [pat for pat, _ in meta.get("patterns", [])]
    for cat, meta in CATEGORY_REGISTRY.items()
}
CATEGORY_DESCRIPTIONS = {
    cat: meta["description"] for cat, meta in CATEGORY_REGISTRY.items()
}
CATEGORY_KEYWORD_MAP = {
    cat: meta.get("synonyms", []) for cat, meta in CATEGORY_REGISTRY.items()
}
CATEGORY_PROMPTS = {
    cat: meta["prompt"] for cat, meta in CATEGORY_REGISTRY.items()
}

# Normalization helpers
SYNONYM_TO_CATEGORY: Dict[str, str] = {}
for cat, meta in CATEGORY_REGISTRY.items():
    SYNONYM_TO_CATEGORY[cat.lower()] = cat
    for syn in meta.get("synonyms", []):
        SYNONYM_TO_CATEGORY[syn.lower()] = cat


def normalize_category_hint(hint: Optional[str]) -> Optional[str]:
    """Convert a free-form category hint to the canonical registry key."""
    if not hint:
        return None
    key = str(hint).strip().lower()
    return SYNONYM_TO_CATEGORY.get(key)


def get_categories_api_payload() -> List[Dict[str, Any]]:
    """Return category list payload used by the frontend sidebar and command bar."""
    return [
        {
            "name": cat,
            "description": meta["description"],
            "priority": meta.get("priority", 50),
        }
        for cat, meta in CATEGORY_REGISTRY.items()
    ]


# Pre-compiled category regex patterns for ultra-fast matching
COMPILED_CATEGORY_PATTERNS: Dict[str, List[Tuple[re.Pattern, int]]] = {
    cat: [
        (re.compile(pat, re.IGNORECASE), weight)
        for pat, weight in meta.get("patterns", [])
    ]
    for cat, meta in CATEGORY_REGISTRY.items()
}


def score_text_against_registry(text: str) -> Dict[str, int]:
    """Score every category against normalized text using pre-compiled weighted patterns."""
    normalized = re.sub(r"[^a-zA-Z0-9\s]+", " ", text).lower()
    scores: Dict[str, int] = {cat: 0 for cat in CATEGORIES}
    for cat, compiled in COMPILED_CATEGORY_PATTERNS.items():
        for regex, weight in compiled:
            if regex.search(normalized):
                scores[cat] += weight
    return scores


def score_text_with_matches(text: str) -> Tuple[Dict[str, int], Dict[str, List[str]]]:
    """Score categories and record the specific matched patterns for transparent explanation."""
    normalized = re.sub(r"[^a-zA-Z0-9\s]+", " ", text).lower()
    scores: Dict[str, int] = {cat: 0 for cat in CATEGORIES}
    matches: Dict[str, List[str]] = {cat: [] for cat in CATEGORIES}

    for cat, compiled in COMPILED_CATEGORY_PATTERNS.items():
        for regex, weight in compiled:
            m = regex.search(normalized)
            if m:
                scores[cat] += weight
                matches[cat].append(f"'{m.group(0)}'")

    return scores, matches


def resolve_category_tie(scores: Dict[str, int]) -> str:
    """Pick best category from weighted scores, breaking ties by priority."""
    max_score = max(scores.values())
    if max_score == 0:
        return "Other"
    candidates = [cat for cat, s in scores.items() if s == max_score]
    if len(candidates) == 1:
        return candidates[0]
    return max(
        candidates,
        key=lambda c: CATEGORY_REGISTRY[c].get("priority", 50),
    )
